# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiscreens.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 30, 611, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginpage = QtWidgets.QWidget()
        self.loginpage.setObjectName("loginpage")
        self.label = QtWidgets.QLabel(self.loginpage)
        self.label.setGeometry(QtCore.QRect(266, 30, 71, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.loginpage)
        self.lineEdit.setGeometry(QtCore.QRect(220, 80, 171, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.loginpage)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 130, 171, 23))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.loginpage)
        self.pushButton.setGeometry(QtCore.QRect(220, 170, 80, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.loginpage)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 170, 80, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.loginpage)
        self.commandLinkButton.setGeometry(QtCore.QRect(220, 220, 174, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.stackedWidget.addWidget(self.loginpage)
        self.registerpage = QtWidgets.QWidget()
        self.registerpage.setObjectName("registerpage")
        self.label_2 = QtWidgets.QLabel(self.registerpage)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 57, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.registerpage)
        self.lineEdit_3.setGeometry(QtCore.QRect(202, 50, 221, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.registerpage)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 100, 221, 23))
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(self.registerpage)
        self.label_3.setGeometry(QtCore.QRect(280, 150, 57, 15))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.registerpage)
        self.comboBox.setGeometry(QtCore.QRect(250, 170, 111, 23))
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(self.registerpage)
        self.label_4.setGeometry(QtCore.QRect(280, 210, 57, 15))
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(self.registerpage)
        self.radioButton.setGeometry(QtCore.QRect(230, 230, 99, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.registerpage)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 230, 99, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_5 = QtWidgets.QLabel(self.registerpage)
        self.label_5.setGeometry(QtCore.QRect(266, 270, 71, 20))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.registerpage)
        self.checkBox.setGeometry(QtCore.QRect(230, 300, 85, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.registerpage)
        self.checkBox_2.setGeometry(QtCore.QRect(300, 300, 85, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.registerpage)
        self.checkBox_3.setGeometry(QtCore.QRect(390, 300, 85, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.registerpage)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 340, 80, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.registerpage)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(10, 10, 174, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.stackedWidget.addWidget(self.registerpage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.commandLinkButton.clicked.connect(MainWindow.goToRegister)
        self.commandLinkButton_2.clicked.connect(MainWindow.goToLogin)
        self.pushButton_3.clicked.connect(MainWindow.onRegister)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login Here"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset"))
        self.commandLinkButton.setText(_translate("MainWindow", "New User? Register"))
        self.label_2.setText(_translate("MainWindow", "Register"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.label_3.setText(_translate("MainWindow", "Country"))
        self.label_4.setText(_translate("MainWindow", "Gender"))
        self.radioButton.setText(_translate("MainWindow", "Male"))
        self.radioButton_2.setText(_translate("MainWindow", "Female"))
        self.label_5.setText(_translate("MainWindow", "Preferences"))
        self.checkBox.setText(_translate("MainWindow", "Travel"))
        self.checkBox_2.setText(_translate("MainWindow", "Shopping"))
        self.checkBox_3.setText(_translate("MainWindow", "Sports"))
        self.pushButton_3.setText(_translate("MainWindow", "Register"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Back"))

